config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  concern :paginatable, Paginatable.new(action: :show)

  resources :expenses, except: [ :show ]
  resource :expenses, only: [] do
    concerns :paginatable, action: :index
  end

  resources :statement_processings, only: [ :update ]
  resources :statements, except: [ :show ]
  resources :statements, only: [], concerns: :paginatable

  resources :sources, except: [ :show ]
  resources :sources, only: [], concerns: :paginatable

  resources :categories, except: [ :show ] do
    resources :subcategories, except: [ :show ]
    resources :subcategories, only: [], concerns: :paginatable
  end
  resources :categories, only: [], concerns: :paginatable
  namespace :bulk do
    resource :expenses, only: [ :update, :destroy ]
  end

  resources :dashboards, only: [ :index ], controller: "dashboards/dashboards"
  namespace :dashboards do
    resources :doughnuts, only: [] do
      collection do
        get :statement
        get :dates
      end
    end
    resources :bars, only: [] do
      collection do
        get :daily
      end
    end
  end

  resource :api, only: [] do
    collection do
      get :total
      get :monthly
    end
  end

  resource :api_access, path: "access", only: [ :edit, :update ] do
    collection do
      put :toogle
    end
  end

  resource :session, only: [ :new, :create, :destroy ]
  resource :password, only: [ :edit, :update ]
  resource :registration, only: [ :new, :create, :destroy ] do
    get :delete
  end

  # Defines the root path route ("/")
  root "home#index"
  get "policy" => "guest#policy", :as => :policy

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :expenses, dependent: :destroy

  def update(params)
    if self.name_was == "Uncategorized"
      self.errors.add("This subcategory", "cannot be changed")
      return false
    end
    super params
  end

  def destroy!
    return false if self.name == "Uncategorized" && !destroyed_by_association
    super
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: %i[ show edit update destroy ]
  before_action :set_category, only: %i[ index show new create edit update destroy ]
  before_action { set_active_page("home") }

  # GET /subcategories or /subcategories.json
  def index
    @subcategories = policy_scope(Subcategory).where(category_id: @category.id)
    @breadcrumb = [ { name: "Home", path: root_path }, { name: "Categories", path: categories_path }, { name: @category.name, path: category_path(@category) }, { name: "Sub-categories" } ]
  end

  # GET /subcategories/1 or /subcategories/1.json
  def show
    page = params[:page]||1
    @paginated_expenses = @subcategory.expenses.paginate(page: page).order(date: :asc)
    @breadcrumb = [ { name: "Home", path: root_path }, { name: "Categories", path: categories_path }, { name: @category.name, path: category_path(@category) }, { name: "Sub-categories", path: category_subcategories_path(@category) }, { name: @subcategory.name } ]
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
    @breadcrumb = [ { name: "Home", path: root_path }, { name: "Categories", path: categories_path }, { name: @category.name, path: category_path(@category) }, { name: "Sub-categories", path: category_subcategories_path(@category) }, { name: "New" } ]
  end

  # GET /subcategories/1/edit
  def edit
    @breadcrumb = [ { name: "Home", path: root_path }, { name: "Categories", path: categories_path }, { name: @category.name, path: category_path(@category) }, { name: "Sub-categories", path: category_subcategories_path(@category) }, { name: @subcategory.name, path: category_subcategory_path(@category, @subcategory) }, { name: "Edit" } ]
  end

  # POST /subcategories or /subcategories.json
  def create
    @subcategory = Subcategory.new(subcategory_params)
    @subcategory.category = @category
    @subcategory.user = Current.user

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to category_subcategories_path(@category), notice: "Subcategory was successfully created." }
        format.json { render :show, status: :created, location: @subcategory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategories/1 or /subcategories/1.json
  def update
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to category_subcategory_path(@category, @subcategory), notice: "Subcategory was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @subcategory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1 or /subcategories/1.json
  def destroy
    respond_to do |format|
      if @subcategory.destroy!
        format.html { redirect_to category_subcategories_path(@category), notice: "Subcategory was successfully destroyed.", status: :see_other }
        format.json { head :no_content }
      else
        format.html { redirect_to category_subcategories_path(@category), alert: "Subcategory cannot be destroyed.", status: :see_other }
        format.json { render json: "Subcategory cannot be destroyed.", status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      params.permit(:id, :subcategory_id)
      @subcategory = Subcategory.find(params[:id] || params[:subcategory_id])
      authorize @subcategory
    end

    def set_category
      @category = Category.find(params.expect(:category_id))
      authorize @category, policy_class: SubcategoryPolicy
    end

    # Only allow a list of trusted parameters through.
    def subcategory_params
      params.expect(subcategory: [ :name, :description ])
    end
end

app/views/subcategories/_form.html.haml
= form_for [@category, @subcategory] do |f|
  - if @subcategory.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subcategory.errors.count, "error")} prohibited this subcategory from being saved:"
      %ul
        - @subcategory.errors.full_messages.each do |message|
          %li= message

  .field.mb-3
    = f.label :name, {class: "form-label"}
    = f.text_field :name, class: "form-control"

  .field.mb-3
    = f.label :description, {class: "form-label"}
    = f.text_field :description, class: "form-control"
  
  .actions.mb-3
    = f.submit 'Save', class: "form-control btn btn-fakturo btn-fakturo-action"

app/views/subcategories/edit.html.haml
%h1 Editing subcategory

.container.w-50

  = render 'form'

app/views/subcategories/index.html.haml
- unless @category.name == "Uncategorized"
  = link_to 'New Sub-category', new_category_subcategory_path, {class: "btn btn-fakturo btn-fakturo-action float-end"}

%h1 Sub-categories
%p
  Category:
  = @category.name

%table.table
  %thead
    %tr
      %th Name
      %th Description
      %th # of expenses
      %th

  %tbody
    - @subcategories.each do |subcategory|
      %tr
        %td= subcategory.name
        %td= subcategory.description
        %td= "#{subcategory.expenses.valid.count}/#{subcategory.expenses.count}"
        %td
          %a{ :href => "#{category_subcategory_page_path(subcategory.category, subcategory)}", "data-bs-toggle" => "tooltip", "data-bs-placement" => "left", "data-bs-title" => "Show details" }
            %svg.bi.pe-none.me-2{ :width => "16", :height => "16", "aria-hidden" => "true" }
              %use{ "xlink:href" => "#three-dots" }
       

app/views/subcategories/new.html.haml
%h1 New subcategory

.container.w-50

  = render 'form'

app/views/subcategories/show.html.haml
%h1
  Sub-category details

.container.w-50
  %table.table
    %thead
      %tr
        %th Info
        %th Value
    %tbody
      %tr
        %td Name
        %td= @subcategory.name
      %tr
        %td Description
        %td= @subcategory.description
      %tr
        %td # of expenses
        %td= "#{@subcategory.expenses.valid.count}/#{@subcategory.expenses.count}"
      - unless @category.name == "Uncategorized"
        %tr
          %td{colspan: "2"}
            = link_to 'Edit this sub-category', edit_category_subcategory_path(@subcategory.category, @subcategory), class: "btn btn-light form-control"
        %tr
          %td{colspan: "2"}
            %button.btn.btn-danger.form-control{:type => "button", "data-bs-toggle" => "modal", "data-bs-target" => "#deleteModal"}
              Delete this sub-category
  
= render partial: "layouts/delete_modal", locals: {element: "sub-category", link: category_subcategory_path(@subcategory.category, @subcategory)}

- if @subcategory.expenses.count > 0
  %hr
  = render partial: "expenses/table", locals: {expenses: @paginated_expenses, show: %i[ statement source ]}