config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  concern :paginatable, Paginatable.new(action: :show)

  resources :expenses, except: [ :show ]
  resource :expenses, only: [] do
    concerns :paginatable, action: :index
  end

  resources :statement_processings, only: [ :update ]
  resources :statements, except: [ :show ]
  resources :statements, only: [], concerns: :paginatable

  resources :sources, except: [ :show ]
  resources :sources, only: [], concerns: :paginatable

  resources :categories, except: [ :show ] do
    resources :subcategories, except: [ :show ]
    resources :subcategories, only: [], concerns: :paginatable
  end
  resources :categories, only: [], concerns: :paginatable
  namespace :bulk do
    resource :expenses, only: [ :update, :destroy ]
  end

  resources :dashboards, only: [ :index ], controller: "dashboards/dashboards"
  namespace :dashboards do
    resources :doughnuts, only: [] do
      collection do
        get :statement
        get :dates
      end
    end
    resources :bars, only: [] do
      collection do
        get :daily
      end
    end
  end

  resource :api, only: [] do
    collection do
      get :total
      get :monthly
    end
  end

  resource :api_access, path: "access", only: [ :edit, :update ] do
    collection do
      put :toogle
    end
  end

  resource :session, only: [ :new, :create, :destroy ]
  resource :password, only: [ :edit, :update ]
  resource :registration, only: [ :new, :create, :destroy ] do
    get :delete
  end

  # Defines the root path route ("/")
  root "home#index"
  get "policy" => "guest#policy", :as => :policy

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action { set_active_page("home") }

  def index
  end
end

app/views/home/access.html.haml
%h1 External access

.container.w-50

  %table.table
    %thead
      %tr
        %th Info
        %th Value
    %tbody
      %tr
        %td Username
        %td= Current.user.username
      %tr
        %td User unique identifier
        %td= Current.user.uuid
      %tr
        %td User access token
        %td= Current.user.access_token
      %tr
        %td User access token expiration date
        %td= Current.user.access_token_expiry_date
      %tr
        %td External access status
        %td{:class => "#{Current.user.access_token_enabled ? 'bg-success-subtle' : 'bg-danger-subtle'}"}
          = Current.user.access_token_enabled ? 'Enabled' : 'Disabled'
      %tr
        %td{colspan: "2"}
          = link_to 'Regenerate token', user_access_regenerate_path, class: "btn btn-light form-control", data: {turbo_method: :put}
      %tr
        %td{colspan: "2"}
          = link_to 'Enable/disable external access', user_access_toogle_path, class: "btn btn-light form-control", data: {turbo_method: :put}

- if Current.user.access_token_enabled
  .accordion#accordionExpenses
    .accordion-item
      %h2.accordion-header
        %button.accordion-button.collapsed{:type => "button", "data-bs-toggle" => "collapse", "data-bs-target" => "#collapseOne", "aria-expanded" => "false", "aria-controls" => "collapseOne"}
          Available external access endpoints
      #collapseOne.accordion-collapse.collapse{"data-bs-parent" => "#accordionExpenses"}
        .accordion-body
          %table.table
            %thead
              %tr
                %th Description
                %th Link
            %tbody
              %tr
                %td Total of expenses by category and subcategory
                %td= link_to "Link", api_total_path(uuid: Current.user.uuid, access_token: Current.user.access_token)
              %tr
                %td Monthly expenses by category and subcategory
                %td= link_to "Link", api_monthly_path(uuid: Current.user.uuid, access_token: Current.user.access_token)

app/views/home/delete.html.haml
%h1 Erase all user data

%div.text-start.mt-3.alert.alert-warning{:role => "alert"}
  %h5
    Caution
  %hr
  The button below will erase all user data. This action is irreversible. If you are concerned about user data usage and privacy, please consult
  = link_to "Data & Privacy policy", policy_path
  
.accordion#accordionExpenses
  .accordion-item
    %h2.accordion-header
      %button.accordion-button.collapsed{:type => "button", "data-bs-toggle" => "collapse", "data-bs-target" => "#collapseOne", "aria-expanded" => "false", "aria-controls" => "collapseOne"}
        I wish to proceed and erase all my data
    #collapseOne.accordion-collapse.collapse{"data-bs-parent" => "#accordionExpenses"}
      .accordion-body
        %div.text-start.mt-3.alert.alert-danger{:role => "alert"}
          You will not be prompted to confirm after clicking in the button below. Proceed with caution.
        = link_to "Erase everything", destroy_data_path, class: "btn btn-danger form-control", data: {turbo_method: :delete}
  

app/views/home/index.html.haml
= link_to "New Statement", new_statement_path, {class: "btn btn-fakturo btn-fakturo-action float-end"}
%h1 My panel
%p Use the options below to manage your data

.row.row-cols-1.row-cols-md-2.g-4
  
  .col.d-flex.align-items-stretch
    .card.w-100
      .card-body.d-flex.flex-column
        %h5.card-title
          Categories
        %p.card-text
          Each expense belongs to a category and a subcategory.
          %a{"data-bs-toggle" => "tooltip", "data-bs-placement" => "top", "data-bs-title" => "Example: expenses for a car can belong to the category \"transportation\" and one of the following subcategories: \"fuel\", \"maintenance\" or \"repair\". "}
            %svg.bi.pe-none.me-2{ :width => "16", :height => "16", "aria-hidden" => "true" }
              %use{ "xlink:href" => "#info" }
        = link_to "Manage categories", categories_path, {class: "btn btn-fakturo align-self-stretch mt-auto"}

  .col.d-flex.align-items-stretch
    .card.w-100
      .card-body.d-flex.flex-column
        %h5.card-title 
          Sources
        %p.card-text
          Sources of expenses, like checking accounts and credit cards.
          %a{"data-bs-toggle" => "tooltip", "data-bs-placement" => "top", "data-bs-title" => "They can be registered as \"Bank X\" and \"Credit card Y\" and will be linked to the expenses. Sources emit statements."}
            %svg.bi.pe-none.me-2{ :width => "16", :height => "16", "aria-hidden" => "true" }
              %use{ "xlink:href" => "#info" }
        = link_to "Manage sources", sources_path, {class: "btn btn-fakturo align-self-stretch mt-auto"}
  
  .col.d-flex.align-items-stretch
    .card.w-100
      .card-body.d-flex.flex-column
        %h5.card-title 
          Statements
        %p.card-text
          Statements are collections of expenses.
          %a{"data-bs-toggle" => "tooltip", "data-bs-placement" => "top", "data-bs-title" => "They belong to an institution (source) and are produced in a regular interval, usually monthly. Think of \"Statement for the month of april from Bank X\"."}
            %svg.bi.pe-none.me-2{ :width => "16", :height => "16", "aria-hidden" => "true" }
              %use{ "xlink:href" => "#info" }
        .alert.alert-info
          When you upload a statement, the expenses it contains will be automatically extracted and registered in the system.
        = link_to "Manage statements", statements_path, {class: "btn btn-fakturo align-self-stretch mt-auto"}
        

  .col.d-flex.align-items-stretch
    .card
      .card-body.d-flex.flex-column
        %h5.card-title Expenses
        %p.card-text
          Each line in a checking account statement or credit card statement is an expense. 
          %br
          %br
          Here you can manage extracted expenses from uploaded statements or create them manually.
        = link_to "Manage expenses", expenses_path, {class: "btn btn-fakturo align-self-stretch mt-auto"}

app/views/home/password.html.haml
.container.w-50
  .w-100.text-center
    %h2 Change password
    = image_tag("logo.png", alt: "Fakturo", width: "60", height: "60")

  = form_for(User, as: current_user, url: registration_path(current_user), html: { method: :put }) do |f| 
    = render "devise/shared/error_messages", resource: current_user
    
    .field.mb-3
      = f.label :password, {class: "form-label"}
      %i (New password)
      = f.password_field :password, autocomplete: "new-password", class: "form-control"
      - if @minimum_password_length
        %em
          (
          = @minimum_password_length 
          characters minimum)

    .field.mb-3
      = f.label :password_confirmation, {class: "form-label"}
      = f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control"
    

    .field.mb-3
      = f.label :current_password, {class: "form-label"}
      = f.password_field :current_password, autocomplete: "current-password", class: "form-control"
    

    .actions.mb-3
      = f.submit "Save", class: "form-control btn btn-fakturo btn-fakturo-action"