config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  concern :paginatable, Paginatable.new(action: :show)

  resources :expenses, except: [ :show ]
  resource :expenses, only: [] do
    concerns :paginatable, action: :index
  end

  resources :statement_processings, only: [ :update ]
  resources :statements, except: [ :show ]
  resources :statements, only: [], concerns: :paginatable

  resources :sources, except: [ :show ]
  resources :sources, only: [], concerns: :paginatable

  resources :categories, except: [ :show ] do
    resources :subcategories, except: [ :show ]
    resources :subcategories, only: [], concerns: :paginatable
  end
  resources :categories, only: [], concerns: :paginatable
  namespace :bulk do
    resource :expenses, only: [ :update, :destroy ]
  end

  resources :dashboards, only: [ :index ], controller: "dashboards/dashboards"
  namespace :dashboards do
    resources :doughnuts, only: [] do
      collection do
        get :statement
        get :dates
      end
    end
    resources :bars, only: [] do
      collection do
        get :daily
      end
    end
  end

  resource :api, only: [] do
    collection do
      get :total
      get :monthly
    end
  end

  resource :api_access, path: "access", only: [ :edit, :update ] do
    collection do
      put :toogle
    end
  end

  resource :session, only: [ :new, :create, :destroy ]
  resource :password, only: [ :edit, :update ]
  resource :registration, only: [ :new, :create, :destroy ] do
    get :delete
  end

  # Defines the root path route ("/")
  root "home#index"
  get "policy" => "guest#policy", :as => :policy

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/dashboards/bars_controller.rb
class Dashboards::BarsController < Dashboards::DashboardsController
  def daily
    @breadcrumb = [ { name: "Home", path: root_path }, { name: "Dashboards", path: dashboards_path }, { name: "Daily amounts" } ]
    if params[:start_date] && params[:end_date]
      @start_date = params[:start_date]
      @end_date = params[:end_date]
      @expenses = policy_scope(Expense).ordered.valid.between_dates(@start_date, @end_date)
        .select("date as date, COUNT(id) as amount, SUM(value) as value").group(:date)
      @option = bar_line_chart(
        @expenses.map { |e| e[:date] },
        @expenses.map { |e| e[:amount] },
        @expenses.map { |e| e[:value] }
        )
    end
  end

  private
  def bar_line_chart(xAxis, bar, line)
    {
      tooltip: {
        trigger: "axis",
        axisPointer: {
          type: "cross",
          label: {
            backgroundColor: "#283b56"
          }
        }
      },
      xAxis: [
        {
          type: "category",
          boundaryGap: true,
          data: xAxis
        }
      ],
      yAxis: [
        {
          type: "value",
          scale: true,
          name: "Amount",
          max: bar.max || 0 + 1,
          min: 0,
          boundaryGap: [ 0.2, 0.2 ]
        },
        {
          type: "value",
          scale: true,
          name: "Value",
          max: line.max || 0 + 1,
          min: 0,
          boundaryGap: [ 0.2, 0.2 ]
        }
      ],
      series: [
        {
          name: "Amount",
          type: "bar",
          data: bar
        },
        {
          name: "Value",
          type: "line",
          yAxisIndex: 1,
          data: line
        }
      ]
    }
  end
end

app/controllers/dashboards/dashboards_controller.rb
class Dashboards::DashboardsController < ApplicationController
  before_action { set_active_page("dashboards") }

  def index
    @breadcrumb = [ { name: "Home", path: root_path }, { name: "Dashboards" } ]
  end
end

app/controllers/dashboards/doughnuts_controller.rb
class Dashboards::DoughnutsController < Dashboards::DashboardsController
  def statement
    @breadcrumb = [ { name: "Home", path: root_path }, { name: "Dashboards", path: dashboards_path }, { name: "Category by statement" } ]
    @statements = policy_scope(Statement).all
    if params[:statement_id]
      @statement = Statement.find(params[:statement_id])
      authorize @statement, policy_class: StatementPolicy
      @cat = policy_scope(Expense)
        .valid.where(statement: @statement)
        .group_by_category
      @sub = policy_scope(Expense)
        .valid.where(statement: @statement)
        .group_by_subcategory

      @option = double_pie_chart(
        { name: "Categories", data: @cat },
        { name: "Sub-categories", data: @sub }
      )
    end
  end

  def dates
    @breadcrumb = [ { name: "Home", path: root_path }, { name: "Dashboards", path: dashboards_path }, { name: "Category between dates" } ]
    if params[:start_date] && params[:end_date]
      @start_date = params[:start_date]
      @end_date = params[:end_date]
      @cat = policy_scope(Expense)
      .valid.between_dates(@start_date, @end_date)
      .group_by_category
      @sub = policy_scope(Expense)
      .valid.between_dates(@start_date, @end_date)
      .group_by_subcategory

      @option = double_pie_chart(
        { name: "Categories", data: @cat },
        { name: "Sub-categories", data: @sub }
      )
    end
  end

  private

  def double_pie_chart(primary, secondary)
    {
      tooltip: {
        trigger: "item",
        formatter: "{a} <br/>{b}: {c} ({d}%)"
      },
      series: [
        {
          name: primary[:name],
          type: "pie",
          selectedMode: "single",
          radius: [ "45%", "60%" ],
          data: primary[:data]
        }, {
          name: secondary[:name],
          type: "pie",
          selectedMode: "single",
          label: {
            position: "inner",
            fontSize: 14
          },
          radius: [ "13%", "43%" ],
          data: secondary[:data]
        }
      ]
    }
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action { set_active_page("dashboards") }

  def index
    @breadcrumb = [ { name: "Home", path: root_path }, { name: "Dashboards" } ]
  end

  def statement
    @breadcrumb = [ { name: "Home", path: root_path }, { name: "Dashboards", path: dashboards_path }, { name: "Category by statement" } ]
    @statements = policy_scope(Statement).all
    if params[:statement_id]
      @statement = Statement.find(params[:statement_id])
      authorize @statement, policy_class: StatementPolicy
      @cat = policy_scope(Expense).unscoped
        .valid.where(statement_id: params[:statement_id])
        .group_by_category
      @sub = policy_scope(Expense).unscoped
        .valid.where(statement_id: params[:statement_id])
        .group_by_subcategory

      @option = double_pie_chart(
        { name: "Categories", data: @cat },
        { name: "Sub-categories", data: @sub }
      )
    end
  end

  def year
    @breadcrumb = [ { name: "Home", path: root_path }, { name: "Dashboards", path: dashboards_path }, { name: "Category by year" } ]
    if params[:year]
      @cat = policy_scope(Expense)
      .valid.where("cast(strftime('%Y', date) as int) = ?", params[:year])
      .group_by_category
      @sub = policy_scope(Expense)
      .valid.where("cast(strftime('%Y', date) as int) = ?", params[:year])
      .group_by_subcategory

      @option = double_pie_chart(
        { name: "Categories", data: @cat },
        { name: "Sub-categories", data: @sub }
      )
    end
  end

  def month
    @breadcrumb = [ { name: "Home", path: root_path }, { name: "Dashboards", path: dashboards_path }, { name: "Category by month" } ]
    if params[:year] && params[:month]
      @cat = policy_scope(Expense)
      .valid.where("cast(strftime('%Y', date) as int) = ? and cast(strftime('%m', date) as int) = ?", params[:year], params[:month])
      .group_by_category
      @sub = policy_scope(Expense)
      .valid.where("cast(strftime('%Y', date) as int) = ? and cast(strftime('%m', date) as int) = ?", params[:year], params[:month])
      .group_by_subcategory

      @option = double_pie_chart(
        { name: "Categories", data: @cat },
        { name: "Sub-categories", data: @sub }
      )
    end
  end

  private

  def double_pie_chart(primary, secondary)
    {
      tooltip: {
        trigger: "item",
        formatter: "{a} <br/>{b}: {c} ({d}%)"
      },
      series: [
        {
          name: primary[:name],
          type: "pie",
          selectedMode: "single",
          radius: [ "45%", "60%" ],
          data: primary[:data]
        }, {
          name: secondary[:name],
          type: "pie",
          selectedMode: "single",
          label: {
            position: "inner",
            fontSize: 14
          },
          radius: [ "13%", "43%" ],
          data: secondary[:data]
        }
      ]
    }
  end
end

app/views/dashboards/doughnuts/dates.html.haml
%h1 Category between dates

%p Select the dates below

= form_with url: dates_dashboards_doughnuts_path, method: :get do |form|
  .field.d-flex
    .mb-3.w-50.pe-1
      = form.label :start_date, {class: "form-label"}
      = form.date_field :start_date, class: "form-control", value: @start_date
    .mb-3.w-50.ps-1
      = form.label :end_date, {class: "form-label"}
      = form.date_field :end_date, class: "form-control", value: @end_date
  .actions.mb-3
    = form.submit "Update chart", class: "form-control btn btn-fakturo btn-fakturo-action"

#chart.container.w-100.h-100

= render "dashboards/import_echarts"

= render partial: "dashboards/chart", locals: {option: @option}

app/views/dashboards/doughnuts/month.html.haml
%h1 Category by year

%p Select the year and the month

= form_with url: month_dashboards_doughnuts_path, method: :get do |form|
  .field.mb-3
    = form.select :year, [2024, 2025].map { |y| [y, y] }, {selected: params[:year], prompt: "Select a year" },{ class: "form-control" }

  .field.mb-3
    = form.select :month, [1,2,3,4,5,6,7,8,9,10,11,12].map { |m| [ "%02d" % m, m] }, {selected: params[:month], prompt: "Select a month" },{ class: "form-control" }
  
  .actions.mb-3
    = form.submit "Update chart", class: "form-control btn btn-fakturo btn-fakturo-action"

#chart.container.w-100.h-100

= render "dashboards/import_echarts"

= render partial: "dashboards/chart", locals: {option: @option}

app/views/dashboards/doughnuts/statement.html.haml
%h1 Category by statement

%p Select the statement

= form_with url: statement_dashboards_doughnuts_path, method: :get do |form|
  .field.mb-3
    = form.select :statement_id, @statements.map { |s| ["#{s.source.name} (#{s.year}-#{'%02d' % s.month})", s.id] }, {selected: params[:statement_id], prompt: "Select a statement" },{ class: "form-control" }
  
  .actions.mb-3
    = form.submit "Update chart", class: "form-control btn btn-fakturo btn-fakturo-action"

#chart.container.w-100.h-100

= render "dashboards/import_echarts"

= render partial: "dashboards/chart", locals: {option: @option}

app/views/dashboards/doughnuts/year.html.haml
%h1 Category by year

%p Select the year

= form_with url: year_dashboards_doughnuts_path, method: :get do |form|
  .field.mb-3
    = form.select :year, [2024, 2025].map { |y| [y, y] }, {selected: params[:year], prompt: "Select a year" },{ class: "form-control" }
  
  .actions.mb-3
    = form.submit "Update chart", class: "form-control btn btn-fakturo btn-fakturo-action"

#chart.container.w-100.h-100

= render "dashboards/import_echarts"

= render partial: "dashboards/chart", locals: {option: @option}