config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  concern :paginatable, Paginatable.new(action: :show)

  resources :expenses, except: [ :show ]
  resource :expenses, only: [] do
    concerns :paginatable, action: :index
  end

  resources :statement_processings, only: [ :update ]
  resources :statements, except: [ :show ]
  resources :statements, only: [], concerns: :paginatable

  resources :sources, except: [ :show ]
  resources :sources, only: [], concerns: :paginatable

  resources :categories, except: [ :show ] do
    resources :subcategories, except: [ :show ]
    resources :subcategories, only: [], concerns: :paginatable
  end
  resources :categories, only: [], concerns: :paginatable
  namespace :bulk do
    resource :expenses, only: [ :update, :destroy ]
  end

  resources :dashboards, only: [ :index ], controller: "dashboards/dashboards"
  namespace :dashboards do
    resources :doughnuts, only: [] do
      collection do
        get :statement
        get :dates
      end
    end
    resources :bars, only: [] do
      collection do
        get :daily
      end
    end
  end

  resource :api, only: [] do
    collection do
      get :total
      get :monthly
    end
  end

  resource :api_access, path: "access", only: [ :edit, :update ] do
    collection do
      put :toogle
    end
  end

  resource :session, only: [ :new, :create, :destroy ]
  resource :password, only: [ :edit, :update ]
  resource :registration, only: [ :new, :create, :destroy ] do
    get :delete
  end

  # Defines the root path route ("/")
  root "home#index"
  get "policy" => "guest#policy", :as => :policy

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :subcategories, dependent: :destroy
  has_many :expenses, dependent: :destroy

  def update(params)
    if self.name_was == "Uncategorized"
      self.errors.add("This category", "cannot be changed")
      return false
    end
    super params
  end

  def update(params)
    if self.name_was == "Uncategorized"
      self.errors.add("This category", "cannot be changed")
      return false
    end
    super params
  end

  def destroy!
    return false if self.name == "Uncategorized" && !destroyed_by_association
    super
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action { set_active_page("home") }

  # GET /categories or /categories.json
  def index
    @categories = policy_scope(Category).all
    @breadcrumb = [ { name: "Home", path: root_path }, { name: "Categories" } ]
  end

  # GET /categories/1 or /categories/1.json
  def show
    page = params[:page]||1
    @paginated_expenses = @category.expenses.paginate(page: page).order(date: :asc)
    @breadcrumb = [ { name: "Home", path: root_path }, { name: "Categories", path: categories_path }, { name: @category.name } ]
  end

  # GET /categories/new
  def new
    @category = Category.new
    @breadcrumb = [ { name: "Home", path: root_path }, { name: "Categories", path: categories_path }, { name: "New" } ]
  end

  # GET /categories/1/edit
  def edit
    @breadcrumb = [ { name: "Home", path: root_path }, { name: "Categories", path: categories_path }, { name: @category.name, path: category_path(@category) }, { name: "Edit" } ]
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = Current.user

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    respond_to do |format|
      if @category.destroy!
        format.html { redirect_to categories_path, notice: "Category was successfully destroyed.", status: :see_other }
        format.json { head :no_content }
      else
        format.html { redirect_to categories_path, alert: "Category cannot be destroyed.", status: :see_other }
        format.json { render json: "Category cannot be destroyed.", status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      params.permit(:id, :category_id)
      @category = Category.find(params[:id] || params[:category_id])
      authorize @category
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [ :name, :description ])
    end
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |message|
          %li= message

  .field.mb-3
    = f.label :name, {class: "form-label"}
    = f.text_field :name, class: "form-control"

  .field.mb-3
    = f.label :description, {class: "form-label"}
    = f.text_field :description, class: "form-control"
  
  .actions.mb-3
    = f.submit 'Save', class: "form-control btn btn-fakturo btn-fakturo-action"

app/views/categories/edit.html.haml
%h1 Editing category

.container.w-50

  = render 'form'

app/views/categories/index.html.haml
= link_to 'New Category', new_category_path, {class: "btn btn-fakturo btn-fakturo-action float-end"}

%h1 Categories

%table.table
  %thead
    %tr
      %th Name
      %th Description
      %th # of sub-categories
      %th # of expenses
      %th
  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= category.description
        %td= category.subcategories.count
        %td= "#{category.expenses.valid.count}/#{category.expenses.count}"
        %td
          %a{ :href => "#{category_page_path(category.id)}", "data-bs-toggle" => "tooltip", "data-bs-placement" => "left", "data-bs-title" => "Show details" }
            %svg.bi.pe-none.me-2{ :width => "16", :height => "16", "aria-hidden" => "true" }
              %use{ "xlink:href" => "#three-dots" }

app/views/categories/new.html.haml
%h1 New category

.container.w-50

  = render 'form'

app/views/categories/show.html.haml
%h1
  Category details

.container.w-50
  %table.table
    %thead
      %tr
        %th Info
        %th Value
    %tbody
      %tr
        %td Name
        %td= @category.name
      %tr
        %td Description
        %td= @category.description
      %tr
        %td # of sub-categories
        %td= @category.subcategories.count
      %tr
        %td # of expenses
        %td= "#{@category.expenses.valid.count}/#{@category.expenses.count}"
      %tr
        %td{colspan: "2"}
          = link_to 'Manage sub-categories', category_subcategories_path(@category), class: "btn btn-light form-control"
      - unless @category.name == "Uncategorized"
        %tr
          %td{colspan: "2"}
            = link_to 'Edit this category', edit_category_path(@category), class: "btn btn-light form-control"
        %tr
          %td{colspan: "2"}
            %button.btn.btn-danger.form-control{:type => "button", "data-bs-toggle" => "modal", "data-bs-target" => "#deleteModal"}
              Delete this category
  
= render partial: "layouts/delete_modal", locals: {element: "category", link: @category}

- if @category.expenses.count > 0
  %hr
  = render partial: "expenses/table", locals: {expenses: @paginated_expenses, show: %i[ statement source subcategory ]}